version: "3"

services:
  sensors-fake-server:
    image: sensors-fake-server
    command: npm run dev
    build: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: sensors-fake-server
    ports:
      - 3000:3000
    environment:
      ENVIRONMENT: development
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    