version: "3"

services:
  sensors-fake-server:
    image: sensors-fake-server
    command: npm run dev
    build: server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: sensors-fake-server
    ports:
      - 3000:3000
    environment:
      ENVIRONMENT: development
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001